[features]
seeds = false
skip-lint = false
[programs.devnet]
tweet_rust_solana = "2xDB16BQmvgio1Q36iTVRqUhZq9Hqf66681hASZHuiVp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/forever/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
